export const shops = [
    {
        id: 1,
        name: "ベーカリー大泉",
        area: "東京都",
        station: "大泉学園駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 2,
        name: "パンの森",
        area: "大阪府",
        station: "天王寺駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 3,
        name: "ふわふわパン屋",
        area: "神奈川県",
        station: "横浜駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 4,
        name: "パンクラフト",
        area: "北海道",
        station: "札幌駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 5,
        name: "麦の香り",
        area: "愛知県",
        station: "名古屋駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 6,
        name: "フレンチベーカリー",
        area: "京都府",
        station: "四条駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 7,
        name: "甘いパン屋",
        area: "福岡県",
        station: "博多駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 8,
        name: "天然酵母パン",
        area: "東京都",
        station: "新宿駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 9,
        name: "おいしいパン工房",
        area: "大阪府",
        station: "梅田駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 10,
        name: "元気パン",
        area: "兵庫県",
        station: "三宮駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 11,
        name: "カントリーパン",
        area: "奈良県",
        station: "奈良駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 12,
        name: "本格パン工房",
        area: "千葉県",
        station: "船橋駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 13,
        name: "パン屋の木",
        area: "埼玉県",
        station: "川越駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 14,
        name: "フワフワベーカリー",
        area: "宮城県",
        station: "仙台駅",
        image: "https://picsum.photos/800",
    },
    {
        id: 15,
        name: "こだわりパン屋",
        area: "広島県",
        station: "広島駅",
        image: "https://picsum.photos/800",
    },
];
