export const shops = [
    {
        id: 1,
        name: "ベーカリー大泉",
        area: "東京都",
        station: "大泉学園駅",
        image: "https://picsum.photos/800",
        detail: "ベーカリー大泉は、新鮮なパンを提供することに情熱を注いでいる店舗です。地元の人々に愛されるパン屋で、特に「ふわふわ食パン」と「クリームパン」が人気。毎日焼きたてのパンを提供し、季節限定のパンも取り揃えています。店内は広々としたスペースがあり、落ち着いた雰囲気でパンを楽しむことができます。",
        address: "東京都練馬区大泉学園町1-2-3",
        phone: "03-1234-5678",
        hours: "10:00〜18:00",
        holiday: "毎週水曜日",
        instagram: "@bakery_oizumi",
        hp: "https://bakery-oizumi.com",
    },
    {
        id: 2,
        name: "パンの森",
        area: "大阪府",
        station: "天王寺駅",
        image: "https://picsum.photos/800",
        detail: "パンの森は、木々に囲まれた癒しの空間で、焼きたての美味しいパンを提供しています。地元産の素材を活かし、特にライ麦パンやベーグルに力を入れており、ヘルシー志向のお客様にも喜ばれています。また、毎月新作パンが登場し、その都度新しい味を楽しむことができます。店舗内のカフェスペースで、パンをその場で味わえるのも魅力です。",
        address: "大阪府大阪市天王寺区堀越町1-4",
        phone: "06-9876-5432",
        hours: "9:00〜17:00",
        holiday: "毎月第2火曜日",
        instagram: "@pan_no_mori",
        hp: "https://pannomori.com",
    },
    {
        id: 3,
        name: "ふわふわパン屋",
        area: "神奈川県",
        station: "横浜駅",
        image: "https://picsum.photos/800",
        detail: "ふわふわパン屋は、その名の通り、ふわふわのパンを作ることにこだわったベーカリーです。毎朝焼きたてのパンが並び、特に「ふわふわミルクパン」や「チョコチップメロンパン」は常連客にも大人気。店舗内は温かい雰囲気で、ゆっくりとパンを楽しむことができます。パン作りには天然酵母を使用し、こだわりの製法で焼き上げています。",
        address: "神奈川県横浜市西区南幸2-8-15",
        phone: "045-1234-5678",
        hours: "7:30〜18:00",
        holiday: "毎週月曜日",
        instagram: "@fuwafwapanya",
        hp: "https://fuwafwapanya.com",
    },
    {
        id: 4,
        name: "パンクラフト",
        area: "北海道",
        station: "札幌駅",
        image: "https://picsum.photos/800",
        detail: "パンクラフトは、地元の北海道産の小麦を使用したクラフト系のパンが特徴の店舗です。特に「ライ麦パン」や「シナモンロール」が評判で、地元の人々から愛されています。店内にはおしゃれなカフェスペースもあり、パンと一緒にコーヒーも楽しめます。毎月変わる季節限定のパンも楽しみの一つです。",
        address: "北海道札幌市中央区北3条西2-1",
        phone: "011-2345-6789",
        hours: "8:00〜18:00",
        holiday: "毎週火曜日",
        instagram: "@punkraft_bakery",
        hp: "https://punkraft.com",
    },
    {
        id: 5,
        name: "麦の香り",
        area: "愛知県",
        station: "名古屋駅",
        image: "https://picsum.photos/800",
        detail: "麦の香りは、全てのパンに愛知産の小麦を使用し、香り高いパンを提供しています。特に「クロワッサン」や「あんぱん」が人気で、外はサクサク、中はふわふわとした食感が特徴です。お店はこじんまりとしており、温かみのある空間で、ゆっくりとパンを楽しむことができます。",
        address: "愛知県名古屋市中村区名駅南1-2-3",
        phone: "052-3456-7890",
        hours: "9:00〜17:00",
        holiday: "毎週水曜日",
        instagram: "@muginokaori",
        hp: "https://muginokaori.com",
    },
    {
        id: 6,
        name: "フレンチベーカリー",
        area: "京都府",
        station: "四条駅",
        image: "https://picsum.photos/800",
        detail: "フレンチベーカリーは、フランス直輸入のレシピを元に、上質な素材を使用した本格的なフランスパンを提供しているお店です。特に「バゲット」や「クロワッサン」が評判で、店内にはフレンチカフェのような雰囲気があります。朝食にもぴったりなパンを取り揃え、日々新鮮なパンを焼き上げています。",
        address: "京都府京都市下京区四条通高倉西入ル梅湯町560-1",
        phone: "075-1234-5678",
        hours: "7:30〜17:00",
        holiday: "毎週月曜日",
        instagram: "@french_bakery_kyoto",
        hp: "https://frenchbakerykyoto.com",
    },
    {
        id: 7,
        name: "甘いパン屋",
        area: "福岡県",
        station: "博多駅",
        image: "https://picsum.photos/800",
        detail: "甘いパン屋は、特に甘い系のパンが特徴のお店です。クリームパンやメロンパン、チョコレートを使ったパンが大人気で、毎日焼きたてのパンが並びます。店内は明るく、子ども連れのファミリーにも人気のスポットです。また、季節ごとの限定パンも楽しめます。",
        address: "福岡県福岡市博多区博多駅前1-1-1",
        phone: "092-9876-5432",
        hours: "8:00〜18:00",
        holiday: "毎週水曜日",
        instagram: "@amai_panya",
        hp: "https://amaipan.com",
    },
    {
        id: 8,
        name: "天然酵母パン",
        area: "東京都",
        station: "新宿駅",
        image: "https://picsum.photos/800",
        detail: "天然酵母パンは、こだわりの天然酵母を使用し、長時間発酵させたパンが特徴のお店です。特に「ライ麦パン」や「カンパーニュ」が評判で、パンの味わい深さに定評があります。店内には落ち着いたカフェスペースもあり、パンと一緒にこだわりのコーヒーを楽しめます。",
        address: "東京都新宿区新宿3-5-6",
        phone: "03-3456-7890",
        hours: "9:00〜18:00",
        holiday: "毎月第1火曜日",
        instagram: "@tennenkoubo_pan",
        hp: "https://tennenkoubo-pan.com",
    },
    {
        id: 9,
        name: "おいしいパン工房",
        area: "大阪府",
        station: "梅田駅",
        image: "https://picsum.photos/800",
        detail: "おいしいパン工房は、その名の通り、美味しさにこだわったパン屋です。特に「カレーパン」や「ピザパン」が人気で、サクサクの生地と濃厚な具が絶妙にマッチしています。毎日焼きたてのパンが並び、忙しい朝でも立ち寄りやすいお店です。",
        address: "大阪府大阪市北区梅田3-4-5",
        phone: "06-7890-1234",
        hours: "8:00〜17:00",
        holiday: "毎週日曜日",
        instagram: "@oishiipan_koubou",
        hp: "https://oishiipan.com",
    },
    {
        id: 10,
        name: "元気パン",
        area: "兵庫県",
        station: "三宮駅",
        image: "https://picsum.photos/800",
        detail: "元気パンは、毎日新鮮なパンを提供している人気のベーカリーです。特に「元気食パン」や「ミルククリームパン」が人気で、地元の人々にも愛され続けています。店内には大きなオーブンがあり、焼きたてのパンを店内でそのまま楽しむことができます。",
        address: "兵庫県神戸市中央区三宮町1-10-15",
        phone: "078-2345-6789",
        hours: "9:00〜18:00",
        holiday: "毎週水曜日",
        instagram: "@genki_pan",
        hp: "https://genkipan.com",
    },
    {
        id: 11,
        name: "花のパン屋",
        area: "東京都",
        station: "池袋駅",
        image: "https://picsum.photos/800",
        detail: "花のパン屋は、フラワーアレンジメントと共に、焼きたてのパンを楽しむことができるユニークなパン屋です。店内にはおしゃれな花々が飾られ、パンの香りと共にリラックスした空間が広がります。特に「ガーデンベーカリー」と呼ばれる花を使ったパンや、地元のフルーツを使ったパンが人気です。",
        address: "東京都豊島区池袋2-12-9",
        phone: "03-5678-9012",
        hours: "9:00〜19:00",
        holiday: "毎週月曜日",
        instagram: "@hananopanya",
        hp: "https://hananopanya.com",
    },
    {
        id: 12,
        name: "わくわくベーカリー",
        area: "埼玉県",
        station: "さいたま新都心駅",
        image: "https://picsum.photos/800",
        detail: "わくわくベーカリーは、毎日新鮮なパンと共に、楽しい気分を提供するお店です。お子様向けの可愛らしい形をしたパンや、地域限定の特製パンが並んでいます。また、店内にはお菓子作りのワークショップも開催されており、家族で楽しむことができます。",
        address: "埼玉県さいたま市中央区新都心2-5-10",
        phone: "048-1234-5678",
        hours: "10:00〜18:00",
        holiday: "毎週火曜日",
        instagram: "@wakuwaku_bakery",
        hp: "https://wakuwakubakery.com",
    },
    {
        id: 13,
        name: "こだわりのパン屋",
        area: "千葉県",
        station: "船橋駅",
        image: "https://picsum.photos/800",
        detail: "こだわりのパン屋は、素材の選定から焼き上げまで、一切妥協しないことにこだわった店舗です。特に「バタークロワッサン」や「フィローネ」など、風味豊かなパンが魅力です。こだわりの製法で焼き上げたパンを毎日提供しており、その美味しさは地元の常連客から愛されています。",
        address: "千葉県船橋市本町1-2-3",
        phone: "047-3456-7890",
        hours: "8:00〜17:00",
        holiday: "毎週日曜日",
        instagram: "@kodawari_no_panya",
        hp: "https://kodawarinopanya.com",
    },
    {
        id: 14,
        name: "みんなのベーカリー",
        area: "広島県",
        station: "広島駅",
        image: "https://picsum.photos/800",
        detail: "みんなのベーカリーは、地域に根ざしたベーカリーで、地元の食材をふんだんに使用したパンを提供しています。店内には地元のアーティストによる作品が展示されており、地域交流の場としても親しまれています。特に「地元野菜を使ったサンドイッチ」や「広島風お好みパン」が人気です。",
        address: "広島県広島市南区大須2-6-8",
        phone: "082-1234-5678",
        hours: "9:00〜18:00",
        holiday: "毎週火曜日",
        instagram: "@minnano_bakery",
        hp: "https://minnanobakery.com",
    },
    {
        id: 15,
        name: "おしゃれベーカリー",
        area: "京都府",
        station: "烏丸駅",
        image: "https://picsum.photos/800",
        detail: "おしゃれベーカリーは、シンプルで洗練されたデザインの店内で、美味しいパンを楽しめるお店です。特に「塩パン」や「オリーブのパン」など、シンプルな材料で素材の味を活かしたパンが評判です。おしゃれなカフェスペースでゆっくりと過ごせるため、女性客にも人気のスポットです。",
        address: "京都府京都市中京区烏丸通錦小路上ル",
        phone: "075-5678-9012",
        hours: "9:00〜18:00",
        holiday: "毎週月曜日",
        instagram: "@oshare_bakery",
        hp: "https://osharebakery.com",
    },
];
